# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-26 17:16
from __future__ import unicode_literals

import datetime
import directory.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('description', models.TextField()),
                ('email', directory.models.TextEmailField(blank=True, max_length=254)),
                ('homepage', directory.models.TextURLField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('honors', models.TextField()),
                ('name', models.TextField()),
                ('post_nominals', models.TextField()),
                ('publish_externally', models.BooleanField()),
                ('start_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('office', models.CharField(blank=True, choices=[('KLA', 'Kampala Office, Central, Uganda'), ('MKN', 'Busia Office, Eastern, Uganda'), ('WAK', 'Gulu Office, Northern, Uganda'), ('MSK', 'Hoima Office, Western, Uganda'), ('KAB', 'Kabale Office, South-Western Uganda')], max_length=2)),
                ('postal_address', models.TextField(blank=True)),
                ('room', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 20, 16, 42, 874395))),
                ('text', models.TextField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Location'),
        ),
    ]
